[package]
name = "old_tv_shader"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", default-features = false, features = [ "bevy_pbr" ] }

[dev-dependencies]
bevy = { version = "0.15.1" }
